---
title: "study 1 data preparation"
date: "06/06/2018"
---

# packages

```{r, warning = FALSE, message = FALSE}

# install.packages("tidyverse")
# install.packages("haven")
library(tidyverse)
library(haven)

```

# data

```{r, warning = FALSE, message = FALSE}

hsb2 <- "data/study1/rawdata/hsb2.sav" %>% read_spss()

```

# mutate all labelled variables into numeric variables

```{r}

# I want this to be numeric, not labelled
class(pull(hsb2, FEMALE))
is.labelled(pull(hsb2, FEMALE))

# mutate_if() mutates any variable where is.labelled(variable) == TRUE
(hsb2 <- mutate_if(hsb2, is.labelled, parse_number))

```

# create mutate numeric variables to character variables

```{r}

hsb2 <- hsb2 %>%
  mutate(gender_lbl = recode(FEMALE, `0` = "Male", `1` = "Female"),
         race_lbl = recode(RACE, `1` = "Hispanic", `2` = "Asian", `3` = "African-American", `4` = "White"),
         ses_lbl = recode_factor(SES, `1` = "Low", `2` = "Middle", `3` = "High"),
         schooltype_lbl = recode(SCHTYP, `1` = "Public", `2` = "Private"),
         program_lbl = recode(PROG, `1` = "General", `2` = "Academic", `3` = "Vocation"))

# print numeric variables next to their character versions 
hsb2 %>%
  select(FEMALE, gender_lbl, RACE, race_lbl, SES, ses_lbl, SCHTYP, schooltype_lbl, PROG, program_lbl)

```

# export cleaned data

```{r}

hsb2 %>%
  write_csv(path = "data/study1/cleandata/hsb2.csv")

# I want to export a cleaned dataset that SPSS users could use, so this dataset replaces NA variables with -9999
# the "." is a placeholder for the dataset; it means, ". = dataset = hsb2"
hsb2 %>%
  replace(is.na(.), -9999) %>% 
  write_csv(path = "data/study1/cleandata/hsb2SPSS.csv")

```


